name: Selenium Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      php:
        image: php:apache
        ports:
          - '3000:80'
        volumes:
          - ./:/var/www/html

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        # Install Chrome and ChromeDriver for Selenium
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        sudo apt-get install -y chromium-chromedriver
        # Set ChromeDriver and browser path for Selenium
        echo "export CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV
        echo "export CHROMEDRIVER_PATH=/usr/lib/chromium-browser/chromedriver" >> $GITHUB_ENV

    - name: Start Stub Server
      run: |
        ls -lah /var/www/html
        echo 'Server is running on port 3000'
        # Start the PHP server in the background
        sudo service apache2 start
        sleep 10  # Wait for server to start

    - name: Run Selenium Tests - Login
      run: |
        python test_login.py
    
    - name: Run Selenium Test - Register
      run: |
        python test_register.py
