name: Selenium Test CI/CD 
 
on: 
  push: 
    branches: 
      - main 
  pull_request: 
    branches: 
      - main 
      
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      php:
        image: php:apache
        ports:
          - '3000:80'
        volumes:
          - ./:/var/www/html

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Start Stub Server
      run: |
        ls -lah /var/www/html
        echo 'Server is running on port 3000'

    - name: Run Selenium Tests - Login
      run: |
        python test/test_login.py

    - name: Run Selenium Test - Register
      run: |
        python test/test_register.py

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: selenium-test-results
        path: path/to/your/results
