name: Selenium Test CI/CD 
 
on: 
  push: 
    branches: 
      - main 
  pull_request: 
    branches: 
      - main 
      
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      php:
        image: php:apache
        ports:
          - '3000:80'
        volumes:
          - ./:/var/www/html
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 3306:3306
        volumes:
          - mysql-data:/var/lib/mysql
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl unzip
        sudo apt-get install -y google-chrome-stable
        CHROME_VERSION=$(google-chrome-stable --version | sed 's/[^0-9]*\([0-9]*\.[0-9]*\.[0-9]*\)/\1/')
        wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Wait for MySQL to start
      run: |
        sleep 30  # Menunggu MySQL mulai sebelum menjalankan inisialisasi

    - name: Initialize Database
      run: |
        mysql -h 127.0.0.1 -u root -p$MYSQL_ROOT_PASSWORD mydb < db/quiz_pengupil.sql

    - name: Start Stub Server
      run: |
        ls -lah /var/www/html
        echo 'Server is running on port 3000'

    - name: Run Selenium Tests - Login
      run: |
        python test/test_login.py

    - name: Run Selenium Test - Register
      run: |
        python test/test_register.py

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: selenium-test-results
        path: ./test-results 
